# Generated by Django 3.2.8 on 2021-10-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_validated',
        ),
    ]
